### ISSUE TITLE
Ошибка при установке [install error]

### ISSUE THREAD

**Issue by ghost** [smartholdem/smartholdem-wallet#1]
ubuntu 16.04
cd smartholdem-wallet-master/ -> npm install
node.js установлен sudo apt-get install nodejs
как понял node.js требуется для установки, можно указать в readme
![image](https://user-images.githubusercontent.com/34754423/39612387-b424947e-4f67-11e8-8060-9d05f976c8ca.png)

**Comment by technologiespro** [comment]
Следуйте инструкции https://github.com/node-hid/node-hid#compiling-from-source
